# Generated by Django 4.2.5 on 2023-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=' ', max_length=200, verbose_name='body'),
        ),
    ]
