# Generated by Django 4.2.5 on 2023-09-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='saves',
        ),
    ]
