# Generated by Django 4.2.5 on 2023-09-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_like_post_likes_rename_save_post_saves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='likes',
        ),
    ]
